apiVersion: v1
data:
  data: |
    ---
    apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
      name: vmware-system-csi
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-csi-manifests
  namespace: {{ .Release.Namespace }}
