apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vsphere-config-secret
  namespace: {{ .Release.Namespace }}
stringData:
  data: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: vsphere-config-secret
      namespace: vmware-system-csi
    stringData:
      csi-vsphere.conf: |+
        [Global]
        insecure-flag = "true" # TODO

        [VirtualCenter "{{ .Values.credentials.vsphere.server }}"]
        user = "{{ .Values.credentials.vsphere.username }}"
        password = "{{ .Values.credentials.vsphere.password }}"
        datacenters = "DC1"

    type: Opaque
type: addons.cluster.x-k8s.io/resource-set


