apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vsphere-cloud-secret
  namespace: {{ .Release.Namespace }}
stringData:
  data: |
    apiVersion: v1
    kind: Secret
    metadata:
      labels:
        component: cloud-controller-manager
        vsphere-cpi-infra: secret
      name: vsphere-cloud-secret
      namespace: kube-system
    stringData:
      {{ .Values.credentials.vsphere.server }}.username: "{{ .Values.credentials.vsphere.username }}"
      {{ .Values.credentials.vsphere.server }}.password: "{{ .Values.credentials.vsphere.password }}"
    type: Opaque
type: addons.cluster.x-k8s.io/resource-set
