apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
    nodepool: nodepool-a
  annotations:
    helm.sh/resource-policy: keep
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Release.Name }}
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
      nodepool: nodepool-a
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
        nodepool: nodepool-a
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: {{ .Release.Name }}-{{ .Values.worker.talosTemplate }}
      clusterName: {{ .Release.Name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
        name: {{ .Release.Name }}-{{ .Values.worker.machineTemplate }}
      version: {{ .Values.cluster.version }}
