apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ .Values.credentials.vsphere.username }}
  password: {{ .Values.credentials.vsphere.password }}
