apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-argocd-repo
  namespace: {{ .Release.Namespace }}
stringData:
  data: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: repo-apps
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
    stringData:
      type: git
      url: https://gitlab.example.com/***/project-group/***/***/onprem-poc/onprem-vsphere.git
      password: ...
      username: ...

type: addons.cluster.x-k8s.io/resource-set
